version: '2'
services:
  db:
    build:
      context: .
      dockerfile: .db.dockerfile
    ports:
      - 3306:3306
  web:
    build:
      context: .
      dockerfile: .web.dockerfile
    ports:
      - 8080:80
      - 621:21
